services:
  postgres:
    image: postgres:16
    container_name: secure_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

      # - ./pg_hba.custom.conf:/pgconf/pg_hba.custom.conf # for prod limit to :ro
      # - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      #  - ./certs/server.crt:/var/lib/postgresql/server.crt:ro
      #  - ./certs/server.key:/var/lib/postgresql/server.key:ro
      # - ./certs/server.key:/var/lib/postgresql/server.key:ro
    command: >
      postgres -c listen_addresses='*' -c ssl=off
